### ISSUE TITLE
Handle setting data to 0 for datasets that don't apply to all countries

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#247]
e.g NT property counts don't apply in Scotland so setting those to 0 doesn't really make sense as it will skew the numbers.

Suspect need a `countries` property on the dataset and if it's present then only fill empty countries listed. Or maybe an exclude countries list as many of the datasets are everywhere but Scotland.

**Comment by zarino** [comment]
> e.g NT property counts don't apply in Scotland so setting those to 0 doesn't really make sense as it will skew the numbers.

I don’t know much about how the data’s currently implemented, but can’t we use `None` or `NULL` or something to represent constituencies with no data in the given dataset? The denominator for the averages would be the `sum(constituency) where not null` (or whatever) and the empty values would be represented as empty strings (rather than zeroes) in the table/CSV output. Maybe I’m oversimplifying!

**Comment by struan** [comment]
May also want to have a `fill_blanks` or `do_not_fill_blanks` depending on how many this applies to as well as the countries thing. Need both as some datasets, e.g. NT property count, require the blanks to be filled but not in Scotland as NT have no properties in Scotland because that's National Trust for Scotland.
