### ISSUE TITLE
Landing pages for Google Ads

### ISSUE THREAD

**Issue by zarino** [mysociety/local-intelligence-hub#370]
- [x] @MyfanwyNixon to try out localintelligencehub.com and come up with ideas on what people might be searching for
- [x] @MyfanwyNixon to write content for landing pages
- [ ] @zarino or @lucascumsille to create landing pages

**Comment by MyfanwyNixon** [comment]
I've done some work on this [here](https://docs.google.com/spreadsheets/d/1VcNJTi7r3Dav81sUTz70Dz7E9DsEiwULWdoPF5TsXY8/edit?usp=sharing).

Before you dig into that sheet, here's a basic explanation, and some questions:

There are two tabs, because I envisage two types of ad (just as there are basically two routes into the LIH site):

- One about local data
- One about national data

For each of these I've divided potential keywords/ads/landing pages into sections:

- Broad concept of LIH
- Public opinion on climate
- Demographics
- Environmental factors (eg flood risk and air/water quality)
- Groups (eg FoE and WI)
- MPs and their stances, memberships, interests etc
- The election
- Energy
- Nature/biodiversity/wildlife

additionally for the national page, keywords around parties.

So that's prospectively 19 seed ad groups; and **19 landing pages** (thinking we can add more of either at a later date, once we've monitored the success or otherwise of these). Worth noting that it's very easy to keep adding keywords and to see which type are performing well; so these ones are off the top of my head, but we can keep adding at any time.

It will also be beneficial to add in some 'responsive' ads which basically take a keyword from a list you upload, and insert it in the ad text.

This will require:
- a list of MPs, concatenated to make keywords such as [MP'S NAME]'s majority
- a list of PLACE NAMES, concatenated to make keywords such as [PLACE NAME] flood risk

Now, for the latter, I suspect people will be searching more on town or county names than constituency names. But I also assume this will be much more fiddly if we link those search terms directly to the relevant page on LIH rather than to an intermediate landing page (where we'd be asking them to input their postcode).

### LANDING PAGES
For discussion but I've drafted some copy that basically fits the same pattern for each:

- Title
- Prompt to put in a postcode
- keyword rich text for SEO purposes
- footer to explain what the LIH is and who built it

We also discussed including a short video to explain how to find the exact data that the keyword would suggest the user is after. If we don't have time for/decide against video I think we could do good things with a series of images and captions.

Please remind me of whether users are going to need to register to see any of this data, as that will affect how we guide them.


I moved that doc into TCC's `LIH launch>Comms` which I hope is an ok location for it, because I don't have permissions to move it now!

**Comment by zarino** [comment]
All sounds good. I’ve left a couple of comments in the spreadsheet.

> Please remind me of whether users are going to need to register to see any of this data, as that will affect how we guide them.

TBC – we still don’t have a finalised list of which member-supllied datasets will be public or private. But I think the vast majority of the stuff you’ve referred to in the proposed adwords and landing pages will all be public. I guess we can do a check later in January, once we have the final list of public/private datasets.

**Comment by MyfanwyNixon** [comment]
>I think the vast majority of the stuff you’ve referred to in the proposed adwords and landing pages will all be public. 

OK, that means that the main purpose of the landing pages will be to a) satisfy Google that we are giving people what they''ve searched for (by matching their keywords carefully) and b) orient them rather than plonking them on a page of data and leaving them to figure out how it works.

**Comment by emilyk383** [comment]
@MyfanwyNixon fyi we'd expect this to come your way after Lucas is done - wide estimate of about a week out from that... _It’d be good to get them done between the “soft” launch this week and the media launch in Feb. ... We’ll also need to schedule in a little bit of 
Myf’s time, after the development work has been done on this, for her to actually set up all the ads by hand._
