### ISSUE TITLE
JS dependencies do not have cache busting

### ISSUE THREAD

**Issue by struan** [mysociety/local-intelligence-hub#398]
This isn't relevant at the moment as we're not updating these but if we do we'll need to get them to add cache busting things. This is a bit complicated as lots of them are included by other Javascript so we'll need to update the scripts?

**Comment by dracos** [comment]
This applies also to your own dependencies? e.g. if you change explore.esm.js, that has a large max-age and so won't get updated because its URL hasn't changed. So I think it is relevant, unless I've misunderstood.

Django 4.2 adds a `support_js_module_import_aggregation` experimental support for updating import paths as part of compilation. Though I think this should probably be compiled anyway, which would deal with this at that point, commenting on this elsewhere

**Comment by struan** [comment]
This is fixed in https://github.com/mysociety/local-intelligence-hub/commit/7c15ba3cd4000ed5b0c4c98e831ec2eb7d16cae9
