### ISSUE TITLE
Remove duplicates / out of date data in public opinion category

### ISSUE THREAD

**Issue by juliacush** [mysociety/local-intelligence-hub#568]
- [x] Remove old ‘considering voting in general election’ stats
- [x] Remove/update ‘next leader of the Conservative party’? As it was (presumably) done during the Liz Truss era? 
- [ ] Can support (offshore wind / onshore wind / etc) data be made into one bar chart?
- [x] Remove reference to Rishi Sunak’s government

**Comment by struan** [comment]
I've hidden the following:

* Considering voting for a different party in the next General Election to the one they voted for in 2019
* Would prefer the next leader of the Conservative Party to invest in renewable energy
* Think that Rishi Sunak and the Conservative Government do not understand the impact the cost of living crisis is having on people

Not sure if there are more to hide but those felt like the obvious ones to hide.

**Comment by struan** [comment]
I've also marked this as hidden for now while we wait for data:

* APPG membership
* MP job titles
* Select committee membership

I think "Can support (offshore wind / onshore wind / etc) data be made into one bar chart?" is a separate ticket.

Otherwise this just needs @zarino or @juliacush to check if anything else needs to be hidden.

**Comment by zarino** [comment]
Closing in favour of https://github.com/mysociety/local-intelligence-hub/issues/597
